export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_CLOSED: 'JOB_CLOSED',
  APPLICATION_DUPLICATE: 'APPLICATION_DUPLICATE',
  APPLICATION_NOT_ELIGIBLE: 'APPLICATION_NOT_ELIGIBLE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  RESUME_INVALID: 'RESUME_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export default ERROR_CODES;
